// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using FleetSyncManager.Infrastrucure.Persistence.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace FleetSyncManager.Infrastrucure.Persistence
{
    public partial class FleetSyncManagerDbContext : DbContext
    {
        public FleetSyncManagerDbContext()
        {
        }

        public FleetSyncManagerDbContext(DbContextOptions<FleetSyncManagerDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Affectation> Affectations { get; set; }
        public virtual DbSet<Conducteur> Conducteurs { get; set; }
        public virtual DbSet<Deplacement> Deplacements { get; set; }
        public virtual DbSet<Entretien> Entretiens { get; set; }
        public virtual DbSet<Incident> Incidents { get; set; }
        public virtual DbSet<LigneDepense> LigneDepenses { get; set; }
        public virtual DbSet<Vehicule> Vehicules { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Scaffolding:ConnectionString", "Data Source=(local);Initial Catalog=FleetSyncManagerDatabase;Integrated Security=true");

            modelBuilder.Entity<Affectation>(entity =>
            {
                entity.Property(e => e.AffectationId).HasColumnName("AffectationID");

                entity.Property(e => e.ConducteurId).HasColumnName("ConducteurID");

                entity.Property(e => e.DateDebut).HasColumnType("datetime");

                entity.Property(e => e.DateFin).HasColumnType("datetime");

                entity.Property(e => e.VehiculeId).HasColumnName("VehiculeID");

                entity.HasOne(d => d.Conducteur)
                    .WithMany(p => p.Affectations)
                    .HasForeignKey(d => d.ConducteurId)
                    .HasConstraintName("FK__Affectati__Condu__37A5467C");

                entity.HasOne(d => d.Vehicule)
                    .WithMany(p => p.Affectations)
                    .HasForeignKey(d => d.VehiculeId)
                    .HasConstraintName("FK__Affectati__Vehic__38996AB5");
            });

            modelBuilder.Entity<Conducteur>(entity =>
            {
                entity.HasIndex(e => e.PermisConduire, "UQ__Conducte__7B05915D2C7DBAC6")
                    .IsUnique();

                entity.Property(e => e.ConducteurId).HasColumnName("ConducteurID");

                entity.Property(e => e.DateEmbauche).HasColumnType("date");

                entity.Property(e => e.DateNaissance).HasColumnType("date");

                entity.Property(e => e.Nom).HasMaxLength(50);

                entity.Property(e => e.PermisConduire).HasMaxLength(20);

                entity.Property(e => e.Prenoms).HasMaxLength(50);
            });

            modelBuilder.Entity<Deplacement>(entity =>
            {
                entity.Property(e => e.DeplacementId).HasColumnName("DeplacementID");

                entity.Property(e => e.ConducteurId).HasColumnName("ConducteurID");

                entity.Property(e => e.DateArrivee).HasColumnType("datetime");

                entity.Property(e => e.DateDepart).HasColumnType("datetime");

                entity.Property(e => e.LieuArrivee).HasMaxLength(256);

                entity.Property(e => e.LieuDepart).HasMaxLength(256);

                entity.Property(e => e.VehiculeId).HasColumnName("VehiculeID");

                entity.HasOne(d => d.Conducteur)
                    .WithMany(p => p.Deplacements)
                    .HasForeignKey(d => d.ConducteurId)
                    .HasConstraintName("FK__Deplaceme__Condu__2B3F6F97");

                entity.HasOne(d => d.Vehicule)
                    .WithMany(p => p.Deplacements)
                    .HasForeignKey(d => d.VehiculeId)
                    .HasConstraintName("FK__Deplaceme__Vehic__2A4B4B5E");
            });

            modelBuilder.Entity<Entretien>(entity =>
            {
                entity.Property(e => e.EntretienId).HasColumnName("EntretienID");

                entity.Property(e => e.Cout).HasColumnType("decimal(10, 2)");

                entity.Property(e => e.DateEntretien).HasColumnType("datetime");

                entity.Property(e => e.Description).HasMaxLength(255);

                entity.Property(e => e.TypeEntretien).HasMaxLength(50);

                entity.Property(e => e.VehiculeId).HasColumnName("VehiculeID");

                entity.HasOne(d => d.Vehicule)
                    .WithMany(p => p.Entretiens)
                    .HasForeignKey(d => d.VehiculeId)
                    .HasConstraintName("FK__Entretien__Vehic__34C8D9D1");
            });

            modelBuilder.Entity<Incident>(entity =>
            {
                entity.Property(e => e.IncidentId).HasColumnName("IncidentID");

                entity.Property(e => e.ConducteurId).HasColumnName("ConducteurID");

                entity.Property(e => e.DateIncident).HasColumnType("datetime");

                entity.Property(e => e.Description).HasMaxLength(255);

                entity.Property(e => e.VehiculeId).HasColumnName("VehiculeID");

                entity.HasOne(d => d.Conducteur)
                    .WithMany(p => p.Incidents)
                    .HasForeignKey(d => d.ConducteurId)
                    .HasConstraintName("FK__Incident__Conduc__2F10007B");

                entity.HasOne(d => d.Vehicule)
                    .WithMany(p => p.Incidents)
                    .HasForeignKey(d => d.VehiculeId)
                    .HasConstraintName("FK__Incident__Vehicu__2E1BDC42");
            });

            modelBuilder.Entity<LigneDepense>(entity =>
            {
                entity.Property(e => e.LigneDepenseId).HasColumnName("LigneDepenseID");

                entity.Property(e => e.DateDepense).HasColumnType("datetime");

                entity.Property(e => e.Description).HasMaxLength(255);

                entity.Property(e => e.Montant).HasColumnType("decimal(10, 2)");

                entity.Property(e => e.VehiculeId).HasColumnName("VehiculeID");

                entity.HasOne(d => d.Vehicule)
                    .WithMany(p => p.LigneDepenses)
                    .HasForeignKey(d => d.VehiculeId)
                    .HasConstraintName("FK__LigneDepe__Vehic__31EC6D26");
            });

            modelBuilder.Entity<Vehicule>(entity =>
            {
                entity.HasIndex(e => e.Immatriculation, "UQ__Vehicule__E15BDED2C3E63DAE")
                    .IsUnique();

                entity.Property(e => e.VehiculeId).HasColumnName("VehiculeID");

                entity.Property(e => e.DateAchat).HasColumnType("date");

                entity.Property(e => e.Immatriculation).HasMaxLength(20);

                entity.Property(e => e.Marque).HasMaxLength(128);

                entity.Property(e => e.Modele).HasMaxLength(128);

                entity.Property(e => e.Statut).HasMaxLength(20);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}