// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FleetSyncManager.Infrastrucure.Persistence.Entities
{
    public partial class Vehicule
    {
        public Vehicule()
        {
            Affectations = new HashSet<Affectation>();
            Deplacements = new HashSet<Deplacement>();
            Entretiens = new HashSet<Entretien>();
            Incidents = new HashSet<Incident>();
            LigneDepenses = new HashSet<LigneDepense>();
        }

        public int VehiculeId { get; set; }
        public string Marque { get; set; }
        public string Modele { get; set; }
        public int? Annee { get; set; }
        public string Immatriculation { get; set; }
        public DateTime? DateAchat { get; set; }
        public string Statut { get; set; }

        public virtual ICollection<Affectation> Affectations { get; set; }
        public virtual ICollection<Deplacement> Deplacements { get; set; }
        public virtual ICollection<Entretien> Entretiens { get; set; }
        public virtual ICollection<Incident> Incidents { get; set; }
        public virtual ICollection<LigneDepense> LigneDepenses { get; set; }
    }
}